// SEO Configuration and Schema Markup for Averon Digital
import { Metadata } from 'next';

// Base URL configuration
export const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://averon.agency';

// Default SEO configuration
export const defaultSEO: Metadata = {
  metadataBase: new URL(baseUrl),
  title: {
    default: 'Averon | Web Development Agency in Albania | Next.js & React Experts',
    template: '%s | Averon Digital',
  },
  description: 'Leading web development agency in Tirana, Albania. We build modern, high-performance websites using Next.js, React & Django. Custom web solutions for Albanian businesses. Fast, SEO-optimized, mobile-responsive websites that drive results.',
  keywords: [
    // English keywords
    'web development albania',
    'web design tirana',
    'web agency albania',
    'next js albania',
    'react development albania',
    'website development tirana',
    'ecommerce development albania',
    'SEO optimization albania',
    'digital agency tirana',
    'custom website albania',
    'web developer tirana',
    'software development albania',
    'mobile app development albania',
    'responsive web design',
    'modern website design',
    // Albanian keywords
    'agjensi web',
    'agjensi digjitale',
    'krijimi faqesh interneti',
    'dizajn web shqiperi',
    'zhvillim web tirane',
    'faqe interneti profesionale',
    'dizajn modern',
    'optimizim SEO shqip',
    'e-commerce shqiperi',
    'website responsive',
    'zhvillim software',
    'aplikacione web',
  ],
  authors: [{ name: 'Averon Digital', url: baseUrl }],
  creator: 'Averon Digital',
  publisher: 'Averon Digital',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: baseUrl,
  },
  openGraph: {
    type: 'website',
    locale: 'en_AL',
    alternateLocale: ['sq_AL'], // Albanian language
    url: baseUrl,
    siteName: 'Averon Digital',
    title: 'Averon | Professional Web Development in Albania',
    description: 'Transform your business with cutting-edge web solutions. Next.js, React, Django development by Albania\'s top digital agency. Custom websites, e-commerce, SEO optimization.',
    // Images are auto-generated by app/opengraph-image.tsx
    countryName: 'Albania',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Averon | Web Development Agency Albania',
    description: 'Modern websites built with Next.js & React for Albanian businesses',
    // Images are auto-generated by app/twitter-image.tsx
    creator: '@averondigital',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'QN9a17gsvN_DBDSB7hniWRUx68iG5bx5DivlIzXkptE',
  },
};

// Organization Schema
export const organizationSchema = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  '@id': `${baseUrl}/#organization`,
  name: 'Averon Digital',
  alternateName: ['Averon Web Agency', 'Averon', 'Averon Albania'],
  legalName: 'Averon Digital Agency',
  url: baseUrl,
  logo: {
    '@type': 'ImageObject',
    url: `${baseUrl}/averon_logobg.png`,
    width: 400,
    height: 100,
  },
  image: `${baseUrl}/averon_logobg.png`,
  description: 'Professional web development agency in Albania specializing in Next.js, React, and Django development. We create fast, SEO-optimized, mobile-responsive websites for businesses.',
  slogan: 'Transforming businesses through innovative digital solutions',
  address: {
    '@type': 'PostalAddress',
    streetAddress: 'Rruga e Kavajes',
    addressLocality: 'Tirana',
    addressRegion: 'Tirana',
    postalCode: '1001',
    addressCountry: 'AL',
  },
  geo: {
    '@type': 'GeoCoordinates',
    latitude: 41.3275,
    longitude: 19.8187,
  },
  contactPoint: [
    {
      '@type': 'ContactPoint',
      telephone: '+355-69-123-4567',
      contactType: 'customer service',
      email: 'averonagencyal@gmail.com',
      areaServed: ['AL', 'XK', 'MK', 'ME', 'RS'], // Albania and neighboring countries
      availableLanguage: ['Albanian', 'English'],
      contactOption: 'TollFree',
      hoursAvailable: {
        '@type': 'OpeningHoursSpecification',
        dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
        opens: '09:00',
        closes: '18:00',
      },
    },
    {
      '@type': 'ContactPoint',
      contactType: 'sales',
      email: 'averonagencyal@gmail.com',
      availableLanguage: ['Albanian', 'English'],
    },
  ],
  sameAs: [
    // Add your actual social media URLs here when created
    // 'https://www.facebook.com/averondigital',
    // 'https://www.instagram.com/averondigital',
    // 'https://www.linkedin.com/company/averondigital',
    // 'https://twitter.com/averondigital',
    // 'https://www.youtube.com/@averondigital',
    // 'https://github.com/averondigital',
  ],
  foundingDate: '2024',
  foundingLocation: 'Tirana, Albania',
  numberOfEmployees: {
    '@type': 'QuantitativeValue',
    value: 5,
  },
  areaServed: [
    {
      '@type': 'Country',
      name: 'Albania',
    },
    {
      '@type': 'Country',
      name: 'Kosovo',
    },
    {
      '@type': 'Country',
      name: 'North Macedonia',
    },
  ],
  knowsAbout: [
    'Web Development',
    'Next.js',
    'React',
    'Django',
    'SEO Optimization',
    'E-commerce Development',
    'Mobile-Responsive Design',
    'Website Redesign',
    'Brand Design',
    'Digital Marketing',
  ],
  hasOfferCatalog: {
    '@type': 'OfferCatalog',
    name: 'Web Development Services',
    itemListElement: [
      {
        '@type': 'Offer',
        itemOffered: {
          '@type': 'Service',
          name: 'Custom Website Development',
          serviceType: 'Web Development',
        },
      },
      {
        '@type': 'Offer',
        itemOffered: {
          '@type': 'Service',
          name: 'E-commerce Development',
          serviceType: 'E-commerce',
        },
      },
      {
        '@type': 'Offer',
        itemOffered: {
          '@type': 'Service',
          name: 'SEO Optimization',
          serviceType: 'SEO',
        },
      },
      {
        '@type': 'Offer',
        itemOffered: {
          '@type': 'Service',
          name: 'Website Redesign',
          serviceType: 'Redesign',
        },
      },
    ],
  },
};

// LocalBusiness Schema
export const localBusinessSchema = {
  '@context': 'https://schema.org',
  '@type': 'LocalBusiness',
  '@id': baseUrl,
  name: 'Averon Digital Agency',
  image: `${baseUrl}/averon_logobg.png`,
  telephone: '+355-69-123-4567',
  email: 'averonagencyal@gmail.com',
  address: {
    '@type': 'PostalAddress',
    streetAddress: 'Rruga e Kavajes',
    addressLocality: 'Tirana',
    addressRegion: 'Tirana County',
    postalCode: '1001',
    addressCountry: 'AL',
  },
  geo: {
    '@type': 'GeoCoordinates',
    latitude: 41.3275,
    longitude: 19.8187,
  },
  url: baseUrl,
  openingHoursSpecification: [
    {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
  ],
  priceRange: '€€€',
  aggregateRating: {
    '@type': 'AggregateRating',
    ratingValue: '5',
    reviewCount: '15',
  },
};

// Service Schema
export const serviceSchema = {
  '@context': 'https://schema.org',
  '@type': 'Service',
  serviceType: 'Web Development',
  provider: {
    '@type': 'Organization',
    name: 'Averon Digital',
  },
  areaServed: {
    '@type': 'Country',
    name: 'Albania',
  },
  hasOfferCatalog: {
    '@type': 'OfferCatalog',
    name: 'Web Development Services',
    itemListElement: [
      {
        '@type': 'Offer',
        itemOffered: {
          '@type': 'Service',
          name: 'Custom Website Development',
          description: 'Bespoke website development using Next.js and React',
        },
      },
      {
        '@type': 'Offer',
        itemOffered: {
          '@type': 'Service',
          name: 'E-commerce Development',
          description: 'Full-featured online stores with payment integration',
        },
      },
      {
        '@type': 'Offer',
        itemOffered: {
          '@type': 'Service',
          name: 'SEO Optimization',
          description: 'Search engine optimization for Albanian businesses',
        },
      },
      {
        '@type': 'Offer',
        itemOffered: {
          '@type': 'Service',
          name: 'Website Redesign',
          description: 'Transform outdated websites into modern digital experiences',
        },
      },
    ],
  },
};

// Website Schema
export const websiteSchema = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: 'Averon Digital',
  url: baseUrl,
  potentialAction: {
    '@type': 'SearchAction',
    target: {
      '@type': 'EntryPoint',
      urlTemplate: `${baseUrl}/search?q={search_term_string}`,
    },
    'query-input': 'required name=search_term_string',
  },
};

// FAQ Schema
export const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    {
      '@type': 'Question',
      name: 'What services does Averon offer?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Averon offers custom web development, e-commerce solutions, website redesign, SEO optimization, and brand design services. We specialize in Next.js, React, and Django development.',
      },
    },
    {
      '@type': 'Question',
      name: 'Where is Averon located?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Averon is based in Tirana, Albania, and serves businesses throughout Albania and internationally.',
      },
    },
    {
      '@type': 'Question',
      name: 'How long does it take to build a website?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Project timelines vary based on complexity. A standard business website typically takes 2-4 weeks, while complex e-commerce or custom applications may take 6-12 weeks.',
      },
    },
    {
      '@type': 'Question',
      name: 'Do you offer support after the website is launched?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Yes! We provide lifetime support and updates for all our projects. We are committed to your long-term success.',
      },
    },
  ],
};

// Breadcrumb helper function
export function generateBreadcrumbSchema(items: { name: string; url: string }[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: items.map((item, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      name: item.name,
      item: `${baseUrl}${item.url}`,
    })),
  };
}

// Helper to inject schema into page
export function getSchemaScript(...schemas: object[]) {
  return schemas.map((schema) => ({
    type: 'application/ld+json' as const,
    children: JSON.stringify(schema),
  }));
}
