# Generated by Django 5.2.8 on 2025-11-22 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="Contact's email address", max_length=254, validators=[django.core.validators.EmailValidator(message='Please provide a valid email address')])),
                ('name', models.CharField(help_text="Contact's full name", max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='Name must be at least 2 characters')])),
                ('message', models.TextField(help_text="Contact's message", max_length=5000, validators=[django.core.validators.MinLengthValidator(10, message='Message must be at least 10 characters')])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the contact was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the contact was last updated')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the submitter', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='User agent string of the submitter')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether the contact has been processed')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the contact was processed', null=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='contact_con_created_c00730_idx'), models.Index(fields=['email'], name='contact_con_email_d28c53_idx'), models.Index(fields=['is_processed'], name='contact_con_is_proc_7090f0_idx')],
            },
        ),
    ]
